### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by Reel-Deal** [Asd-g/AviSynth-vsMSharpen#1]
Hi,

I noticed the order of the parameters is not the same as the original avs version. 

Original version:  `int "threshold", int "strength", bool "highq", bool "mask"`
This version: `float "threshold", float "strength", bool "mask", bool "luma", bool "chroma", bool "highq")`

**"highq"** not being in the original order breaks backward compatibility with any script not using named parameters.

**Comment by Asd-g** [comment]
Hi,
In addition to the different parameters order also the output is not identical when default values are used. threshold 5.9 gives identical output.
Might be better to rename the plugin (file + function name) to something like vs_MSharpen because threshold and strength parameters are quite different between that version and the original one?

**Comment by Reel-Deal** [comment]
That's a very good point. Changing both plugin and function name would keep the original and updated version separate, and won't break anything :)
